name: DotNetPad
on:
  push:
    paths: 
      - 'src/**'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: dotnet build ./src/DotNetPad/DotNetPad.sln -c Release
