name: DotNetPad
on:
  push:
    paths: 
      - 'src/**'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      run: msbuild ./src/DotNetPad/DotNetPad.sln /restore /p:Configuration=Release /p:GenerateAppxPackageOnBuild=false
